CREATE TABLE actor(
   name   VARCHAR(24) NOT NULL PRIMARY KEY
);
INSERT INTO actor(name) VALUES ('Bill Paxton');
INSERT INTO actor(name) VALUES ('David Brisbin');
INSERT INTO actor(name) VALUES ('Max Elliott Slade');
INSERT INTO actor(name) VALUES ('Greg Brown');
INSERT INTO actor(name) VALUES ('Sam Anderson');
INSERT INTO actor(name) VALUES ('Nora Dunfee');
INSERT INTO actor(name) VALUES ('Jean Speegle Howard');
INSERT INTO actor(name) VALUES ('Brett Rice');
INSERT INTO actor(name) VALUES ('Margo Moorer');
INSERT INTO actor(name) VALUES ('Christopher Jones');
INSERT INTO actor(name) VALUES ('Michael Mattison');
INSERT INTO actor(name) VALUES ('Don Rickles');
INSERT INTO actor(name) VALUES ('Afemo Omilami');
INSERT INTO actor(name) VALUES ('Roger Corman');
INSERT INTO actor(name) VALUES ('Jim Lovell');
INSERT INTO actor(name) VALUES ('Haley Joel Osment');
INSERT INTO actor(name) VALUES ('Troy Christian');
INSERT INTO actor(name) VALUES ('Tom Hanks');
INSERT INTO actor(name) VALUES ('Ed Harris');
INSERT INTO actor(name) VALUES ('Sally Field');
INSERT INTO actor(name) VALUES ('Annie Potts');
INSERT INTO actor(name) VALUES ('Timothy McNeil');
INSERT INTO actor(name) VALUES ('Mark Matheisen');
INSERT INTO actor(name) VALUES ('David Andrews');
INSERT INTO actor(name) VALUES ('Jacqueline Lovell');
INSERT INTO actor(name) VALUES ('Brendan Shanahan');
INSERT INTO actor(name) VALUES ('Laurie Metcalf');
INSERT INTO actor(name) VALUES ('Jim Varney');
INSERT INTO actor(name) VALUES ('Zach Hanner');
INSERT INTO actor(name) VALUES ('Emily Ann Lloyd');
INSERT INTO actor(name) VALUES ('Kathleen Quinlan');
INSERT INTO actor(name) VALUES ('Chris Ellis');
INSERT INTO actor(name) VALUES ('Siobhan Fallon');
INSERT INTO actor(name) VALUES ('George Kelly');
INSERT INTO actor(name) VALUES ('Kirk Ward');
INSERT INTO actor(name) VALUES ('Gary Sinise');
INSERT INTO actor(name) VALUES ('Daniel C. Striepeke');
INSERT INTO actor(name) VALUES ('Andrew Lipschultz');
INSERT INTO actor(name) VALUES ('William Shipman');
INSERT INTO actor(name) VALUES ('Penn Jillette');
INSERT INTO actor(name) VALUES ('Clint Howard');
INSERT INTO actor(name) VALUES ('Vanessa Roth');
INSERT INTO actor(name) VALUES ('Gabriel Jarret');
INSERT INTO actor(name) VALUES ('Michael Burgess');
INSERT INTO actor(name) VALUES ('Michael McFall');
INSERT INTO actor(name) VALUES ('Xander Berkeley');
INSERT INTO actor(name) VALUES ('Hanna Hall');
INSERT INTO actor(name) VALUES ('Christian Clemenson');
INSERT INTO actor(name) VALUES ('Mike Jolly');
INSERT INTO actor(name) VALUES ('Tracy Reiner');
INSERT INTO actor(name) VALUES ('John Voldstad');
INSERT INTO actor(name) VALUES ('Peter Dobson');
INSERT INTO actor(name) VALUES ('Jed Gillin');
INSERT INTO actor(name) VALUES ('Marlena Smalls');
INSERT INTO actor(name) VALUES ('Erik von Detten');
INSERT INTO actor(name) VALUES ('Robb Skyler');
INSERT INTO actor(name) VALUES ('Michael Conner Humphreys');
INSERT INTO actor(name) VALUES ('Bob Penny');
INSERT INTO actor(name) VALUES ('R. Lee Ermey');
INSERT INTO actor(name) VALUES ('Thom Barry');
INSERT INTO actor(name) VALUES ('Wallace Shawn');
INSERT INTO actor(name) VALUES ('Isabel Rose');
INSERT INTO actor(name) VALUES ('Charles Boswell');
INSERT INTO actor(name) VALUES ('Aaron Michael Lacey');
INSERT INTO actor(name) VALUES ('Lazarus Jackson');
INSERT INTO actor(name) VALUES ('Sarah Freeman');
INSERT INTO actor(name) VALUES ('Joe Alaskey');
INSERT INTO actor(name) VALUES ('Robin Wright');
INSERT INTO actor(name) VALUES ('Matt Wallace');
INSERT INTO actor(name) VALUES ('Bryan Hanna');
INSERT INTO actor(name) VALUES ('Tim Allen');
INSERT INTO actor(name) VALUES ('Sonny Shroyer');
INSERT INTO actor(name) VALUES ('Hallie D''Amore');
INSERT INTO actor(name) VALUES ('Al Harrington');
INSERT INTO actor(name) VALUES ('John Ratzenberger');
INSERT INTO actor(name) VALUES ('Joe Spano');
INSERT INTO actor(name) VALUES ('Endre Hules');
INSERT INTO actor(name) VALUES ('Michele Little');
INSERT INTO actor(name) VALUES ('Mark Wheeler');
INSERT INTO actor(name) VALUES ('Tiffany Salerno');
INSERT INTO actor(name) VALUES ('Byron Minns');
INSERT INTO actor(name) VALUES ('John Morris');
INSERT INTO actor(name) VALUES ('Michael Kemmerling');
INSERT INTO actor(name) VALUES ('Richard D''Alessandro');
INSERT INTO actor(name) VALUES ('Brett Cullen');
INSERT INTO actor(name) VALUES ('Michael Jace');
INSERT INTO actor(name) VALUES ('Geoffrey Blake');
INSERT INTO actor(name) VALUES ('Mary Kate Schellhardt');
INSERT INTO actor(name) VALUES ('Kevin Mangan');
INSERT INTO actor(name) VALUES ('Don Fischer');
INSERT INTO actor(name) VALUES ('Steven Griffith');
INSERT INTO actor(name) VALUES ('Dick Cavett');
INSERT INTO actor(name) VALUES ('Stephen Bridgewater');
INSERT INTO actor(name) VALUES ('Kevin Bacon');
INSERT INTO actor(name) VALUES ('Daniel J. Gillooly');
INSERT INTO actor(name) VALUES ('Miko Hughes');
INSERT INTO actor(name) VALUES ('Mary Ellen Trainor');
INSERT INTO actor(name) VALUES ('Kitty K. Green');
INSERT INTO actor(name) VALUES ('John William Galt');
INSERT INTO actor(name) VALUES ('Mykelti Williamson');
